version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexuscore

  nexuscore:
    build: .
    command: python run.py
    ports: ["8000:8000"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgresql+psycopg2://nexus:nexus@postgres:5432/nexuscore
      NEXUS_SERVICE_API_KEY_FILE: /run/secrets/nexus_service_api_key
      NEXUS_SECRET_KEY_FILE: /run/secrets/nexus_secret_key
      NEXUS_BOOTSTRAP_USERS_JSON_FILE: /run/secrets/nexus_bootstrap_users_json
      NEXUS_COOKIE_SECURE: "false"
    depends_on: [kafka, postgres]
    secrets:
      - nexus_service_api_key
      - nexus_secret_key
      - nexus_bootstrap_users_json

secrets:
  nexus_service_api_key:
    file: .secrets/nexus_service_api_key.txt
  nexus_secret_key:
    file: .secrets/nexus_secret_key.txt
  nexus_bootstrap_users_json:
    file: .secrets/nexus_bootstrap_users_json.json

